[package]
name = "fusen-register"
version = "0.9.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/fusen-register"
readme.workspace = true
license-file.workspace = true


[dependencies]
fusen-contract.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["sync"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "time"] }
