#![forbid(unsafe_code)]
#![warn(missing_docs)]
//! Production-oriented JSON RPC runtime for plaintext HTTP/1.1 and h2c.

extern crate self as fusen_rs;

mod client;
mod context;
mod error;
mod middleware;
mod policy;
mod resilience;
mod rpc;
mod runtime;
mod server;
mod service;
mod wire;

pub use client::{
    BreakerThreshold, CircuitBreakerConfig, ClientAdmissionConfig, ClientConfig,
    ClientConfigBuilder, ClientHttpConfig, ClientRuntime, ClientRuntimeBuilder, ClientState,
    DiscoveryConfig, QueueConfig, RetryConfig,
};
pub use context::{Arguments, RpcContext, RpcResponse};
pub use error::{ClientError, ClientErrorKind, ServerError, ServerErrorKind};
pub use fusen_contract as contract;
pub use fusen_contract::{Idempotency, WireProtocol};
pub use fusen_observability::{MetricsRecorder, NoopMetricsRecorder};
pub use fusen_procedural_macro::{method, service};
pub use fusen_register::{RegistrationHandle, Registry, SubscriptionHandle};
pub use middleware::{Middleware, Next, RpcResult};
pub use policy::{InstanceSnapshot, LoadBalancer, Router, WeightedRandom};
pub use resilience::{FailureClass, RetryDecision, RetryDecisionContext, RetryPolicy};
pub use rpc::{ErrorCode, InvalidErrorCode, ProblemDetails, RpcCategory, RpcError, RpcOrigin};
pub use server::{
    HttpServerConfig, RunningServer, Server, ServerBuilder, ServerConfig, ServerConfigBuilder,
    ServerHandle, ServerRegistryConfig, ServerRequestConfig, ServerState,
};

/// Private ABI used exclusively by code generated by `#[service]`.
#[doc(hidden)]
pub mod __macro {
    pub use crate::client::{ServiceClient, ServiceClientBuilder};
    pub use crate::runtime::BoxFuture;
    pub use crate::service::{
        IntoServerService, PreparedService, ServerInvocation, ServerService, decode_argument,
        encode_argument, finish_arguments, method_not_found,
    };
    pub use crate::{
        Arguments, ClientError, ClientRuntime, Idempotency, LoadBalancer, Middleware, Router,
        RpcError, WireProtocol,
    };
    pub use crate::{RpcResponse as ServerResponse, RpcResult};
    pub use fusen_contract::{
        MethodDescriptor, MethodId, ServiceDescriptor, ServiceSelector, SpringCloudMethod,
        SpringCloudParameter, SpringCloudParameterSource,
    };
    pub use http;
}
