[package]
name = "fusen-procedural-macro"
version = "0.9.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/fusen-procedural-macro"
readme = "README.md"
license-file.workspace = true

[lib]
proc-macro = true

[dependencies]
quote.workspace = true
syn = { workspace = true, features = ["full", "visit"] }
proc-macro2.workspace = true
proc-macro-crate.workspace = true

[dev-dependencies]
trybuild.workspace = true

[lints]
workspace = true
