[package]
name = "fusen-nacos"
version = "0.9.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Nacos registration, discovery, and configuration for fusen-rs"
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/fusen-nacos"
readme.workspace = true
license-file.workspace = true

[features]
default = []
yaml = ["fusen-config/yaml"]

[dependencies]
fusen-config.workspace = true
fusen-register.workspace = true
tokio = { workspace = true, features = ["rt", "sync"] }
serde.workspace = true
nacos-sdk.workspace = true
percent-encoding.workspace = true
tracing.workspace = true
url.workspace = true

[dev-dependencies]
http.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time"] }
