[package]
name = "fusen-rs"
version = "0.9.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/fusen-rs"
readme = "README.md"
license-file.workspace = true


[dependencies]
fusen-procedural-macro.workspace = true
fusen-contract = { workspace = true, features = ["derive"] }
fusen-register.workspace = true
fusen-observability.workspace = true
serde.workspace = true
serde_json = { workspace = true, features = ["raw_value"] }
thiserror.workspace = true
tokio = { workspace = true, features = [
    "rt",
    "macros",
    "net",
    "sync",
    "time",
    "signal",
    "io-util",
] }
tokio-util = { workspace = true, features = ["rt"] }
futures-util.workspace = true
tracing.workspace = true
uuid = { workspace = true, features = ["v4"] }

#网络协议处理
http.workspace = true
httpdate.workspace = true
bytes.workspace = true
http-body-util.workspace = true
hyper = { workspace = true, features = ["client", "server", "http1", "http2"] }
hyper-util = { workspace = true, features = ["client-legacy", "server-auto", "tokio"] }
tower-service.workspace = true
hyper-rustls.workspace = true
rustls.workspace = true
rand.workspace = true
urlencoding.workspace = true
url.workspace = true
mime.workspace = true

[dev-dependencies]
fusen-config.workspace = true
rcgen.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "test-util"] }
tokio-rustls.workspace = true

[[bench]]
name = "invocation"
harness = false

[lints]
workspace = true
