[package]
name = "examples"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true
publish = false

[lints]
workspace = true


[[bin]]
name = "host-server"
path = "src/host/server.rs"

[[bin]]
name = "host-client"
path = "src/host/client.rs"

[[bin]]
name = "host-client-pt"
path = "src/host/client_pt.rs"

[[bin]]
name = "host-server-pt"
path = "src/host/server_pt.rs"

[[bin]]
name = "nacos-server"
path = "src/nacos/server.rs"

[[bin]]
name = "nacos-client"
path = "src/nacos/client.rs"

[[bin]]
name = "nacos-hot-config"
path = "src/nacos/hot_config.rs"


[dependencies]
tokio = { workspace = true, features = [
    "macros",
    "rt-multi-thread",
    "signal",
    "sync",
    "time",
] }
serde.workspace = true
serde_json.workspace = true

fusen-rs.workspace = true
fusen-config = { workspace = true, features = ["yaml"] }
fusen-nacos = { workspace = true, features = ["yaml"] }
fusen-observability.workspace = true
rand.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
