[package]
name = "fusen-derive-macro"
version = "0.9.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/fusen-derive-macro"
readme.workspace = true
license-file.workspace = true


[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0.36"
syn = { version = "2.0.71", features = ["full"] }
